RegisterCommand("pegaid", function()
    local pid = PlayerPedId()
    print("ID:"..pid)
end)

RegisterCommand("pegacorcabelo", function()
    local pid = PlayerPedId()
    local color = GetPedHairColor(pid)
    print("Cor do cabelo:"..color)
end)